name: Release on PyPI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch, tag or SHA to release from"
        required: true
        default: "master"

jobs:
  build-and-publish:
    name: Build and publish
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install poetry
      run: pip install -U poetry

    - name: Install dependencies
      run: poetry install

    - name: Build package
      run: poetry build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        repository-url: https://test.pypi.org/legacy/
